# Generated by Django 4.1.4 on 2023-01-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phno',
            new_name='Phno',
        ),
    ]
